migrated to zio 2
ScalaConsultants/zio-akka-http-interop pull request #125
Opened 2022-07-06 11:20 UTC by Adriani277

2022-07-07 08:47 UTC, Adriani-Furtado commented
@mayonesa @marioosh @lkuczera @molowny @marekklis @tues @danieletorelli @ptrdom Sorry to spam all of you in a comment but I am not sure who/how to reach out to have this reviewed 🙏

2022-07-07 15:29 UTC, jczuchnowski commented
On it!

2022-07-07 16:34 UTC, jczuchnowski requested changes
Looks good. Just a .gitignore change please.

2022-07-07 16:34 UTC, jczuchnowski commented on .gitignore
> +.vscode
The right place for bloop, metals, bsp and vscode is in the local .gitignore-global.
I'd replace this whole new block with just `project/` because that should take care of `project` directory on every level.

2022-07-14 10:58 UTC, jczuchnowski approved these changes

2022-07-14 11:00 UTC, merged